language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm
before_script:
  - php composer.phar self-update
  - php composer.phar update
script: phpunit --bootstrap src/autoload.php tests
test:
  adapter: mysql
  database: myapp_test
  username: travis
  encoding: utf8